GITHUB_OWNER     = "andrii-sosiuk"
FLUX_GITHUB_REPO = "devops-101-flux"
GOOGLE_PROJECT   = "dron-demo"
GOOGLE_REGION    = "us-central1-c"
GKE_MACHINE_TYPE = "g1-small"
# GKE_NUM_NODES    = "2"
# GKE_CLUSTER_NAME = "main"
# GKE_POOL_NAME    = "main"